version: '3.8'
#seevices are db,app,backup&nginx
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: capstone_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - capstone_net

  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/capstone_db
    networks:
      - capstone_net
    ports:
      - "8000:8000"
  backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    container_name: backup_service
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: capstone_db
    volumes:
      - ./backups:/backup
    networks:
      - capstone_net
    init: true

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - capstone_net

volumes:
  postgres_data:

networks:
  capstone_net:
