# Name of GitHub workflow
name: Capstone CI/CD

# Trigger this workflow on every push to the repository
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint Backup Script
      run: shellcheck backup/search_backup.sh

    - name: Build Docker Images
      run: docker compose build

    - name: Setup SSH and Deploy to VM
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd project && docker compose pull && docker compose up -d"

    - name: Test Endpoints
      run: |
        curl http://localhost:8000/tasks
        curl http://localhost:8080/backups/
