name: Local CI Test

on:
  push:
    branches: ["main"]

jobs:
  test-only:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Lint Backup Script
      run: shellcheck backup/search_backup.sh

    - name: Docker Compose Build
      run: docker compose build

    - name: Run Containers
      run: docker compose up -d

    - name: Run Placeholder Tests
      run: echo "All services running. Manual test required."

    - name: Stop Containers
      run: docker compose down
