# Name of the workflow (shown in GitHub Actions UI)
name: CI/CD Pipeline

# Trigger this workflow on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set Python 3.10 on the runner
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    # Build Docker containers
    - name: Docker Compose Build
      run: docker-compose build

    # Run containers and check if services start (optional)
    - name: Docker Compose Up (optional)
      run: docker-compose up -d

    # You can add test steps here if needed
    - name: Run tests (placeholder)
      run: echo "Tests would run here"

    # Tear down containers after test (optional)
    - name: Docker Compose Down (optional)
      run: docker-compose down
